# -*- coding: utf-8 -*-

import os
import test_server

# -- Travis variables -----------------------------------------------------

travis_home = os.environ.get("HOME", "~/")
travis_build_dir = os.environ.get("TRAVIS_BUILD_DIR", "../..")
travis_repo_slug = os.environ.get("TRAVIS_REPO_SLUG")
travis_repo_shortname = travis_repo_slug.split("/")[1]
odoo_exclude = os.environ.get("EXCLUDE")
odoo_include = os.environ.get("INCLUDE")
odoo_version = os.environ.get("VERSION")
odoo_full = os.environ.get("ODOO_REPO", "odoo/odoo")
server_path = test_server.get_server_path(odoo_full, odoo_version, travis_home)
odoo_addons = test_server.get_addons_to_check(
    travis_build_dir, odoo_include, odoo_exclude)
odoo_addons_path = test_server.get_addons_path(
    travis_home, travis_build_dir, server_path).split(',')

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinxodoo.ext.autodoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = '%s (%s)' % (travis_repo_shortname, odoo_version)
copyright = u'2015, OCA'
author = u'OCA'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = odoo_version
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = project.replace(' ', '-')

# -- Odoo options ---------------------------------------------------------
sphinxodoo_addons = odoo_addons
sphinxodoo_root_path = server_path
sphinxodoo_addons_path = odoo_addons_path
